#!/usr/bin/env php
<?php namespace app;

// running on a the command line?
if (\php_sapi_name() === 'cli')
{
	require 'setup.php';

	Layer::stack
		(
			Layer_TaskRunner::instance()
				->writer(Writer_Console::instance())
				->args($_SERVER['argv'])
		);
}
